### ISSUE TITLE
图片发送异常

### ISSUE THREAD

**Issue by zuojianjian** [leancloud/leancloud-demos#11]
leancloud发送图片消息总是失败，看别人都发送成功是怎么回事，总有一个叹号提示，报空指针异常：                   Caused by: com.avos.avoscloud.AVException: java.lang.NullPointerException: Attempt to get length of null array
                                                                              at com.avos.avoscloud.QiniuUploader.uploadWithBlocks(QiniuUploader.java:126)
                                                                              at com.avos.avoscloud.QiniuUploader.doWork(QiniuUploader.java:70)

**Comment by weakish** [comment]
时间过久，暂时先关掉了。
