### ISSUE TITLE
android sdk bug. v3.15.6 

### ISSUE THREAD

**Issue by LaughingAndroid** [leancloud/leancloud-demos#12]
app在restart的时候会crash，原因是没有initialize。现在问题是因为某种原因，我并不能保证init的比serveice重启的快，你们能不能加固下sdk得代码，日志如下：

```
E/===AVOS Cloud===: LogUtil$avlog->e->39: Please initialize Application first

java.lang.RuntimeException: Unable to create service com.avos.avoscloud.PushService: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                            at android.app.ActivityThread.handleCreateService(ActivityThread.java:3818)
                                                                            at android.app.ActivityThread.access$2100(ActivityThread.java:222)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:158)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                            at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:87)
                                                                            at java.lang.StringBuilder.<init>(StringBuilder.java:95)
                                                                            at com.avos.avoscloud.AVUtils.getSessionKey(AVUtils.java:1056)
                                                                            at com.avos.avoscloud.SessionManager.<init>(SessionManager.java:36)
                                                                            at com.avos.avoscloud.SessionManager.getInstance(SessionManager.java:55)
                                                                            at com.avos.avoscloud.AVSessionCacheHelper.getAllSessionFromLocal(AVSessionCacheHelper.java:102)
                                                                            at com.avos.avoscloud.AVSessionCacheHelper.getAllSession(AVSessionCacheHelper.java:65)
                                                                            at com.avos.avoscloud.AVPushConnectionManager.initSessionsIfExists(AVPushConnectionManager.java:81)
                                                                            at com.avos.avoscloud.AVPushConnectionManager.<init>(AVPushConnectionManager.java:66)
                                                                            at com.avos.avoscloud.AVPushConnectionManager.getInstance(AVPushConnectionManager.java:96)
                                                                            at com.avos.avoscloud.PushService.getConnectionManagerInstance(PushService.java:680)
                                                                            at com.avos.avoscloud.PushService.onCreate(PushService.java:108)
                                                                            at android.app.ActivityThread.handleCreateService(ActivityThread.java:3808)
                                                                            at android.app.ActivityThread.access$2100(ActivityThread.java:222) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:158) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7237) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
```

**Comment by weakish** [comment]
时间过久，暂时先关掉了。如仍碰到类似问题，欢迎到 [LeanCloud论坛][0] 讨论。

[0]: https://forum.leancloud.cn/
